# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Merge with values.yaml for Skaffold-driven local image builds (see skaffold.yaml).
image:
  pullPolicy: IfNotPresent

server:
  sandboxImagePullPolicy: IfNotPresent
  supervisorImagePullPolicy: IfNotPresent
  disableTls: true
