# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "openshell.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshell.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ default (include "openshell.fullname" .) .Values.httpRoute.gatewayName }}
      namespace: {{ default .Release.Namespace .Values.httpRoute.gatewayNamespace }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "openshell.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
